version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: user_service_development
      MYSQL_USER: user_service
      MYSQL_PASSWORD: user_service_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
    networks:
      - app_network

  user-service:
    build:
      context: ./user_service
    container_name: user_service
    restart: always
    stdin_open: true   # - keeps STDIN open so byebug can read your commands
    tty: true 
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
    volumes:
      - ./user_service:/rails
      - /rails/vendor
    networks:
      - app_network

  matching-service:
    build:
      context: ./matching_service
    container_name: matching_service
    restart: always
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://mongo:27017/matching_service
      JWT_SECRET_KEY: your_jwt_key
    volumes:
      - ./matching_service:/app
    networks:
      - app_network

  web:
    build:
      context: ./web
    container_name: web
    restart: always
    ports:
      - "3001:3000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm run dev
    networks:
      - app_network
      
  kong:
    image: kong:3.7           # phiên bản OSS mới nhất, có sẵn DB-less
    container_name: kong
    restart: always
    depends_on:
      - user-service
      - matching-service
    environment:
      KONG_DATABASE: "off"                   # bật DB-less
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    volumes:
      - ./kong/kong.yml:/kong/kong.yml:ro    # mount file cấu hình
    ports:
      - "8000:8000"   # cổng proxy – client/ứng dụng Next.js gọi vào đây
      - "8001:8001"   # cổng admin – bạn gửi lệnh admin API, nếu muốn
    networks:
      - app_network

volumes:
  mysql_data:
  mongo_data:
  mongo_config:

networks:
  app_network:
    driver: bridge
